apiVersion: v1
kind: Pod
metadata:
  name: go-hello
  labels:
    type: go-hello
spec:
  containers:
  - name: api
    image: dellicon/todo:1.0.0
    livenessProbe:
      httpGet:
        path: /this/path/does/not/exist
        port: 8080
      initialDelaySeconds: 5
      timeoutSeconds: 2 # Defaults to 1
      periodSeconds: 5 # Defaults to 10
      failureThreshold: 1 # Defaults to 3